### PR TITLE
Add mention on reqwest in the README.

### PR DESCRIPTION
**Pull request by frewsxcv**

### CODE REVIEW

**Comment by GitCop** [comment]
Thanks for contributing! Unfortunately, I'm here to tell you there were the following style issues with your Pull Request:

 * Commit: cdf28ed4a416376506bd3678a3a20c0421a15be6
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/hyperium/hyper/blob/master/CONTRIBUTING.md

---
This message was auto-generated by https://gitcop.com

**Comment by frewsxcv** [comment]
I'm not particularly fond of the wording here, just sharing the idea. Maybe it should be bold, maybe it should mention 'built-in TLS support', not sure

**Comment by seanmonstar** [comment]
I've actually been reluctant, since it I also maintain reqwest, it feels kind of unfair for hyper to single it out as the thing someone should reach for...

**Comment by frewsxcv** [comment]
It's not clear to me why that's unfair, but no worries

**Pull request closed without merging**
