### PR TITLE
chore(body): pub empty

### PR DESCRIPTION
**Pull request by fundon**
Sometimes we want to replace the body.

```rust
BodyExt::collect(replace(req.body_mut(), IncomingBody::empty()))
```

### CODE REVIEW

**Comment by seanmonstar** [comment]
Thanks for the PR!

We actually recently just made it private, since the type is _only_ meant to represent a body streaming from an IO transport. In the example you mentioned, I would usually `map_body` to put the fully collected body type in, so it becomes `Request<Collected>`.

**Comment by fundon** [comment]
Thanks for the reply.

I'll try the `map_body` method first in my case.

**Comment by fundon** [comment]
My case likes below:

https://github.com/seanmonstar/warp/blob/master/src/route.rs#L130-L140

```rust
    pub(crate) fn take_body(&mut self) -> Option<Body> {
        match self.body {
            BodyState::Ready => {
                let body = mem::replace(self.req.body_mut(), Body::empty());
                self.body = BodyState::Taken;
                Some(body)
            }
            BodyState::Taken => None,
        }
    }
```

**Comment by fundon** [comment]
Other case, if we want to limit the body first.

```rust
let body = Limited::new(req.body_mut(), Body::empty()), 1024);
BodyExt::collect(body).await
```

Maybe adds `Default` trait to `Incoming` would be a good solution.
So we can use `std::mem::take` method to take body.

**Comment by fundon** [comment]
Other way to fix that, just define a enum, includes `None`, `Empty`, `Incoming`, `Stream` fileds.

**Pull request closed without merging**
