### PR TITLE
[WIP] feat(client): add origin config to client builder

### PR DESCRIPTION
**Pull request by gokulchandra**
Took an attempt to provide a solution for #2178 .

I went with the assumption that we'd only want to set when Hyper is used as a Http client.
The `Client::Builder` now has an additional config to accept a value for setting the `Origin` header. Once configured it gets added for every request made.

```
let client = Client::builder()
            .add_origin("http://secret-mission".parse().unwrap())
            .build()
```
Let me know if you think this makes sense. Can iterate on it as required.

### CODE REVIEW

**Comment by seanmonstar** [comment]
Thanks for the PR!

The issue #2178 may not have been super clear. It was meant that we should provide some `hyper::service::AddOrigin` middleware. Something that looks like this (I'm going to skip some imports and things):

```rust
pub struct AddOrigin<S> {
    scheme: http::uri::Scheme,
    auth: http::uri::Authority,
    service: S,
}

impl<Req, S: Service<Req> Service<Req> for AddOrigin {
    // ...
}
```

It's similar to what was done in this commit: https://github.com/tower-rs/tower-http/commit/51cef91f758c1aae672876c2ac1dde93e47e63aa

cc @LucioFranco

**Comment by gokulchandra** [comment]
Ah okay. I misunderstood that. So the intention is to provide a `AddOrigin` middleware agnostic of whether the library is used as a client or server. 

Thanks for the reference, let me update this PR.

**Comment by seanmonstar** [comment]
I'm going to close this PR for now, but feel free to open if you want to make the changes!

**Comment by gokulchandra** [comment]
Fair enough. Will raise a PR once I am done with the changes.

**Pull request closed without merging**
