### PR TITLE
Allow to carry extensions from request to response

### PR DESCRIPTION
**Pull request by DoumanAsh**
As name implies, this PR adds swapping extensions out of `Request` to `Response`

I'm somewhat unsure if you'd like to see it or not, but it should help users to carry extra information specific to _particular_ request.
And it allow users to do so outside of `Connector`

### CODE REVIEW

**Comment by seanmonstar** [comment]
I *believe* I already have existing code that uses some extensions  as flags, and automatically setting them on the `Response` when the conditions of the response didn't match would mess up that logic...

However, it seems like setting the same extensions on the response would be possible with a `Service` middleware, ya?

**Comment by DoumanAsh** [comment]
>I believe I already have existing code that uses some extensions as flags, and automatically setting them on the Response when the conditions of the response didn't match would mess up that logic

Eh is that so?
Can I still use extensions for my needs then? 😄 

I'm actually need it for my client library rather server side (I don't think `Service` applies there)
But if it would be better to remain out of hyper itself, we can close PR

**Comment by seanmonstar** [comment]
> Can I still use extensions for my needs then?

Heh, of course! I didn't mean to emphasize *my* code, so much as if I've written it, I'd suspect others may have too.

And my reference to a `Service` is because I've been spending so much time in tower, where the client is treated like a `Service` as well (and will be eventually). Is it not possible to do what you want outside of hyper?

**Comment by DoumanAsh** [comment]
It should be possible with some extra work as client consumes request, but not impossible I guess

**Comment by DoumanAsh** [comment]
@seanmonstar Btw, I was using extensions to store `sec-websocket-key` which worked quite good😄

**Pull request closed without merging**
