### PR TITLE
feat(error): add additional methods to determine kind

### PR DESCRIPTION
**Pull request by omjadas**
Add additional methods to determine error kind.

### CODE REVIEW

**Comment by seanmonstar** [comment]
Thanks for the PR! I'm generally in favor of having accessor methods to inspect the error more. However, I've also been thinking the current `Kind` enum variants are a little disorganized, and have thought it may warrant an internal cleanup. Are there any variants that you specifically needed to know, or were you just wanting to add methods for all variants?

**Comment by omjadas** [comment]
> Thanks for the PR! I'm generally in favor of having accessor methods to inspect the error more. However, I've also been thinking the current `Kind` enum variants are a little disorganized, and have thought it may warrant an internal cleanup. Are there any variants that you specifically needed to know, or were you just wanting to add methods for all variants?

The ones that I am particularly interested are `Io` and `Shutdown`.

**Comment by omjadas** [comment]
@seanmonstar Just coming back to this. I would be happy to update this PR to only add methods for the `Io` and `Shutdown` error kinds (assuming you are happy with those two) and potentially any others you think should be exposed as well.

**Comment by seanmonstar** [comment]
We'll be going in a different direction, adding a [`Code`](#2845).

**Pull request closed without merging**
