### PR TITLE
Add Error::cause2 and Error::into_error

### PR DESCRIPTION
**Pull request by sfackler**
cause2 is a bad name, but I couldn't think of anything obviously better
off the top of my head.

### CODE REVIEW

**Comment by seanmonstar** [comment]
Related #1542

**Comment by jonhoo** [comment]
@sfackler `cause_static`?

**Comment by jonhoo** [comment]
Also, could we include `as_io_error -> Option<&std::io::Error>` in this patch?

**Comment by sfackler** [comment]
That's just `cause2().and_then(|e| e.downcast_ref::<io::Error>())` - not sure that needs to be a whole separate method.

**Comment by jonhoo** [comment]
@sfackler no, that's not true. While it may be true *currently*, unless `hyper` explicitly guarantees that any `io::Error` will only be nested exactly one deep in the cause hierarchy, that could suddenly start failing as more error nesting is introduced.

**Comment by jonhoo** [comment]
I'm not sure I agree? It's not inconceivable that `hyper` at some point got, say, a `tokio::Error` internally, which then in turn contains an `io::Error`. Or that it uses something like `failure`'s `.context()` which adds a layer of indirection to the `io::Error`. To your second point, I think `io::Error`s are sufficiently special to warrant them being exposed. For example, an error like `AddrInUse` the caller can often recover from by falling back to a non-fixed port.

**Comment by seanmonstar** [comment]
While I don't foresee any plans to add additional types to the chain, the issue you describe could also happen directly inside hyper. We'd need some way to make sure `as_io_error` handled any intermediate types that were added, and it'd be just as easy to miss.

**Comment by jonhoo** [comment]
Absolutely true! But as a consumer of the library, I'm unlikely to know if the internals change. Forcing users to go through `cause` for `io::Error` means that changing the internals of `hyper::Error` may be cause for a breaking semver change if it adds or removes nesting.

**Pull request merged**
