### PR TITLE
TcpStream of CloneTcpStream should be public

### PR DESCRIPTION
**Pull request by apetrelli**
For the sake of extension, I made TcpStream of CloneTcpStream public.

### CODE REVIEW

**Comment by GitCop** [comment]
Thanks for contributing! Unfortunately, I'm here to tell you there were the following style issues with your Pull Request:

 * Commit: 03262d343841ccac2c1a0f9b33fbec1e0b2df389
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: 38d44fc6b36d93661127c160e7109f04b1d65750
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/hyperium/hyper/blob/master/CONTRIBUTING.md

---
This message was auto-generated by https://gitcop.com

**Comment by apetrelli** [comment]
Resolves #529

**Comment by seanmonstar** [comment]
Is there a place where you could access it? I thought I made into_inner()
skip the wrapper.

**Comment by apetrelli** [comment]
I'm trying to extend HttpConnector to support proxies, so I created an attempt of my version of HttpConnector, named HttpProxyConnector, copying code locally. The offending line is this:
Ok(HttpStream::Http(CloneTcpStream(try!(TcpStream::connect(addr)))))

Notice that I am a novice in Rust, so please pardon my lack of precision.

**Comment by seanmonstar** [comment]
Ahhh, I see. Hm, I find `CloneTcpStream` a wart that I'd rather remove.

Question though: would proxy support in the `Client` be useful, or you're using the connectors directly?

**Comment by apetrelli** [comment]
Probably I missed proxy support in client :-D I did not find it in docs, is it there somewhere? If not then probably I should open an issue in the docs :-D

**Comment by seanmonstar** [comment]
No, there isn't proxy support in `Client`, yet. However, it should. And that'd be the best way, since it doesn't really require another connector.

**Comment by seanmonstar** [comment]
@apetrelli ive opened #531 where we can discuss exactly how it should work.

I'm going to close this for now, as I'd rather find a way to remove `CloneTcpStream`, and making that property public may mean more code breaks when I finally do give it the axe.

**Comment by apetrelli** [comment]
Ok fine for me.

**Pull request closed without merging**
