### PR TITLE
Add tests for headers

### PR DESCRIPTION
**Pull request by pyfisch**
Already one bug discovered, I commented out the testcase, it can be fixed later.

### CODE REVIEW

**Comment by pyfisch** [comment]
bug number 2 found.

**Comment by pyfisch** [comment]
Another bug found

**Comment by pyfisch** [comment]
This PR is complete now.

**Comment by seanmonstar** [comment]
Wow, this is looking awesome (viewing on my phone atm)

**Comment by reem** [comment]
@pyfisch should we try to move existing tests into this infrastructure, or is it meant to only be for certain types of tests? Agreed with @seanmonstart that this looks pretty awesome.

**Comment by pyfisch** [comment]
We can move (hopefully) all header tests into the new infrastructure. The macro just supports parsing and formatting, some headers have different tests, but we should be able to write them also inside the new test section. It should be also possible to add `bench_header()` to the section, but I am not sure if we need special bench testcases, I think we could just bench the normal test cases.

**Pull request merged**
