### PR TITLE
fix(net): don't stop the server when an SSL handshake fails with EOF

### PR DESCRIPTION
**Pull request by cyndis**
HttpAcceptor::accept()'s HTTPS logic passes IO errors from the underlying
SSL stream directly to the caller. Furthermore, the caller uses the
EndOfFile error code to detect that the server should stop accepting
connections. This means that if the TCP connection was succesfully
accepted, but an EOF condition was detected during the handshake, the
server will stop accepting connections and quit. This allows for a
trivial denial of service attack and can happen accidentally as well.

Change HttpAcceptor::accept such that if the TCP stream underlying
the SSL stream returns an EndOfFile error, change the error kind
to OtherIoError.

----

The way I fixed this is a bit ugly, but can't think of a nicer and easy way at the moment.
Suggestions welcome.

Cheers,
cyndis

### CODE REVIEW

**Comment by seanmonstar** [comment]
This could also happen to the client, right? Perhaps the logic would be best in `lift_ssl_error`? Also, looking in that function, I see `ConnectionAborted` being used. Perhaps that'd be a better error here as well, instead of `OtherIoError`?

**Comment by cyndis** [comment]
The client can also get an EndOfFile but there it should be handled correctly, here the issue is that the server code thinks the EndOfFile is coming from the acceptor, not the stream. So really, we probably should be turning all IoErrors from the stream in accept() into something else so that they are not confused with IoErrors from the acceptor. I guess ConnectionAborted would be a good choice. That would hide the underlying reason, but I can't think why it would be ever needed.

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 37a71e8634988cc316cbcd8e86a60d2429d9050d
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/hyperium/hyper/blob/master/CONTRIBUTING.md

---
This message was auto-generated by https://gitcop.com

**Comment by cyndis** [comment]
Here's v2 according to what I described in the previous message. I will squash these once the patch is ready.

**Comment by seanmonstar** [comment]
Looks good to me.

**Comment by cyndis** [comment]
Great, I'll squash.

**Comment by cyndis** [comment]
Whoops, something went wrong there..

**Comment by cyndis** [comment]
Fixed.

**Comment by seanmonstar** [comment]
Awesome work, thank you! Just waiting on travis to go green.

**Comment by cyndis** [comment]
Thanks for a great library :)

**Pull request merged**
