### PR TITLE
Add Body::to_vec() convenience method

### PR DESCRIPTION
**Pull request by djc**
Reusing this error is a little ugly, let me know if this makes sense and how you'd want it to look.

### CODE REVIEW

**Comment by nickelc** [comment]
Have you seen [`hyper::body::to_bytes(Body)`](https://docs.rs/hyper/0.13.0/hyper/body/fn.to_bytes.html) or [`hyper::body::aggregate(Body)`](https://docs.rs/hyper/0.13.0/hyper/body/fn.aggregate.html)?

**Comment by djc** [comment]
Ah, no! Managed to miss those. Maybe I'll add a pointer to them in the `Body` docs.

**Comment by seanmonstar** [comment]
I'd rather we just have the `body::{aggregate, to_bytes}` helpers for now. We could add more references to them in the docs, though.

**Comment by djc** [comment]
Makes sense!

**Pull request closed without merging**
