### PR TITLE
fix(rustup): update FromStr

### PR DESCRIPTION
**Pull request by retep998**

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 12746b6076b62dd8167af2670ac345dc2497c36f
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/hyperium/hyper/blob/master/CONTRIBUTING.md

---
This message was auto-generated by https://gitcop.com

**Comment by seanmonstar** [comment]
Wow. :beers:. I was waiting for the `url` crate to be fixed, cause I couldn't compile past that.

**Comment by seanmonstar** [comment]
Just published url, seems to compile locally, poking travis.

**Comment by seanmonstar** [comment]
Almost perfect. Seems there the `core` feature was no longer needed in a benchmark. I've fixed that, amended your commit, and pushed it as #291.

**Pull request closed without merging**
