### PR TITLE
Implement forgotten settings for case preserving

### PR DESCRIPTION
**Pull request by nox**
Turns out I didn't implement the server-side public setters for #2480, oopsie.

### CODE REVIEW

**Comment by zonyitoo** [comment]
What's the differences between `http1_title_case_headers` and `http1_preserve_header_case`?

**Comment by nox** [comment]
`http1_title_case_headers`: `Sec-WebSocket-Key` becomes `Sec-Websocket-Key`.
`http1_preserve_header_case`: `Sec-WebSocket-Key` is sent as is.

Note that you can combine the two, so that existing headers in a given request will preserve their original case, but headers added by Hyper itself (say, `date`) will use the title case.

**Comment by zonyitoo** [comment]
So `http1_title_case_headers` won't make `date` become `Date`?

**Comment by nox** [comment]
It will, but `http1_preserve_header_case` won't on its own, that's why you need the two. *Preserve* means there was an original casing to begin with (i.e. the casing that was found when on the wire when parsing the HTTP message), that's not the case for headers emitted by Hyper itself.

**Comment by nox** [comment]
Also, note that Hyper still doesn't let you pass arbitrary header case, as `HeaderCaseMap` is still private, so `http1_preserve_header_case` is only useful for proxies right now, where you receive a request from one end, and send it with the client on the other end.

**Comment by nox** [comment]
This now includes @zonyitoo's fix from #2510.

**Comment by seanmonstar** [comment]
Thanks for the quick fix!

**Pull request merged**
