### PR TITLE
docs(headers): clarify Basic auth

### PR DESCRIPTION
**Pull request by jethrogb**
See https://tools.ietf.org/html/rfc7617

- [x] The commit messages match the guidelines in https://github.com/hyperium/hyper/blob/master/CONTRIBUTING.md#git-commit-guidelines

### CODE REVIEW

**Comment by seanmonstar** [comment]
Is this actually true? I looked around in RFC 7617, and couldn't find text the stated this. In fact, I suspect it's common for clients to convert a request to `http://user@example.org` into the a basic auth header of `base64("user")`.

**Comment by jethrogb** [comment]
The RFC doesn't leave room for not including the password:
```
   To receive authorization, the client

   1.  obtains the user-id and password from the user,

   2.  constructs the user-pass by concatenating the user-id, a single
       colon (":") character, and the password,

   3.  encodes the user-pass into an octet sequence (see below for a
       discussion of character encoding schemes),

   4.  and obtains the basic-credentials by encoding this octet sequence
       using Base64 ([RFC4648], Section 4) into a sequence of US-ASCII
       characters ([RFC0020]).
```

**Comment by seanmonstar** [comment]
Ah, I see that the code in this type also does that. So then the point is that when decoding, it might not include a colon. Does it make sense to have an `Option` at all? Or should it actually fail parsing if there is no semi colon?

Probably depends on real world usage, instead of exaclty what the spec does.

**Comment by jethrogb** [comment]
> Does it make sense to have an Option at all? Or should it actually fail parsing if there is no semi colon?

What is the behavior for other headers? I thought it'd be ok to be lenient in parsing and just document proper behavior.

**Pull request merged**
