### PR TITLE
feat(http): reexport `http`

### PR DESCRIPTION
**Pull request by sanmai-NL**
For parity with other reexports.

### CODE REVIEW

**Comment by sanmai-NL** [comment]
One test failed locally:
```
failures:

---- client::connect::http::tests::client_happy_eyeballs stdout ----
thread 'client::connect::http::tests::client_happy_eyeballs' panicked at 'assertion failed: `(left == right)`
  left: `4`,
 right: `6`', src/client/connect.rs:1022:17
note: Run with `RUST_BACKTRACE=1` for a backtrace.


failures:
    client::connect::http::tests::client_happy_eyeballs
```
Should be unrelated.

**Comment by seanmonstar** [comment]
So far, I've figured people could depend on the `http` crate directly if they needed the less common types. What do you propose the exports would look like if re-exporting the whole crate?

**Comment by sanmai-NL** [comment]
I’m not sure I understand your last sentence.

**Comment by seanmonstar** [comment]
Ah, sorry. You asked about re-exporting all of `http`. What do propose the export would be? Just `hyper::http`? Or something different?

**Comment by sanmai-NL** [comment]
Yes, just `hyper::http`; as that would be the effect of `pub extern crate ...;`, which I still see as the main way to reexport. It could indeed be something else with `pub use`.

**Comment by seanmonstar** [comment]
I suppose a `pub extern crate http;` would be fine... Would you like to change this PR to do that?

**Comment by sanmai-NL** [comment]
@seanmonstar, done. See also rust-lang-nursery/api-guidelines#176

**Comment by seanmonstar** [comment]
Sorry for forgetting about this, I've made a tiny tweak and merged this manually to master. Thanks!

**Comment by MingweiSamuel** [comment]
d55b5efb890ef04e37825221deae9c57e9e602fa

**Pull request closed without merging**
