### PR TITLE
fix(response): respond with a 500 if a handler panics

### PR DESCRIPTION
**Pull request by Ryman**
It may be worth weakening the check here to only set 500 when the status is still 200 (incase a user wants to return 400 or some other error), but I think being strict here discourages the use of panics for control flow.

### CODE REVIEW

**Comment by seanmonstar** [comment]
This is likely a good idea. Though I'm intrigued that so much can happen after a panic...

**Comment by Ryman** [comment]
cc @reem @untitaker for prior art downstream @ https://github.com/iron/iron/pull/397, may have opinions on this.

**Comment by Ryman** [comment]
@seanmonstar Not sure if that's a genuine appveyor failure? Looks like a timeout on one of them, and the testrunner not completing on the other?

**Comment by untitaker** [comment]
Lgtm. Fwiw iron has a default status code of 500 right now, for the same reason. I guess that can be removed again?

On 30 October 2015 03:11:02 CET, Ryman <notifications@github.com> wrote:
>@seanmonstar Not sure if that's a genuine appveyor failure? Looks like
>a timeout on one of them, and the testrunner not completing on the
>other?
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/hyperium/hyper/pull/676#issuecomment-152388778

-- 
Sent from my phone. Please excuse my brevity.

**Comment by untitaker** [comment]
Nvm I see you've already linked it.

On 30 October 2015 03:11:02 CET, Ryman <notifications@github.com> wrote:
>@seanmonstar Not sure if that's a genuine appveyor failure? Looks like
>a timeout on one of them, and the testrunner not completing on the
>other?
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/hyperium/hyper/pull/676#issuecomment-152388778

-- 
Sent from my phone. Please excuse my brevity.

**Pull request merged**
