### PR TITLE
Other approach to implementing server SSL support

### PR DESCRIPTION
**Pull request by cactorium**
So I wrote another possible way to implement SSL! Lots of good Rust practice. So this approach uses generics and implemented the SSL layer as a wrapper that can be applied to another listener/acceptor/stream. This avoids breaking the `NetworkListener` API, because it instead breaks the `Server` API; there ends up being two possible values returned, based on whether the acceptor ends up being wrapped in the TLS wrappers or not, and I'm not sure how it should be cleaned up. Thoughts? Sorry for bothering you so much!

### CODE REVIEW

**Comment by cactorium** [comment]
What if the listeners were created using a factory:
```
pub trait ListenerFactory<L> {
    pub fn bind(...) -> Box<NetworkListener>;
    pub fn new() -> Self;
}

pub enum HttpListenerFactory<L> {
    Http,
    Https(Path, Path)
}

pub impl ListenerFactory<L> for HttpListenerFactory<L> {
    ...
}

pub struct IdentityListenerFactory<L> { }
pub impl ListenerFactory<L> for ... {
    ...
}

pub struct Server {
    // ...
    listener: Box<ListenerFactory<L>>,
}

impl Server {
    pub fn http(...) -> Server {
        Server::with_listener_factory(..., box HttpListenerFactory::<L>::Http)
    }

    pub fn https(..., key, cert) -> Server {
        Server::with_listener_factory(..., box HttpListenerFactory::<L>::Https(key, cert))
    }

    pub fn with_listener(...) -> Server {
        Server::with_listener_factory(..., box IdentityListenerFactory::<L>::new())
    }

    pub fn with_listener_factory(ip, port, listener: Box<NetworkListener>) -> Server {
        Server::with_listener_factory(..., box HttpListenerFactory::Https(key, cert))
    }
}
```

That way the factory could be used to choose between a custom listener, or the standard Http/Https one, and NetworkListener would work basically like how it does now. Or would that be too complicated?

**Comment by seanmonstar** [comment]
I'm currently switching the traits over to use associated types. I think that will ease this is in.

**Comment by seanmonstar** [comment]
Example:
```rust
trait NetworkListener {
    type Acceptor: NetworkAcceptor;
    // ...
}
```

**Comment by reem** [comment]
Oh man - that will be such an improvement.

**Comment by seanmonstar** [comment]
@cactorium I recently redesigned those traits as I said I would, can you where to plug in the Ssl pieces?

**Comment by cactorium** [comment]
Wow, the code looks a lot cleaner! Gonna read through all of it and see if I can figure it out

**Pull request closed without merging**
