### PR TITLE
Adapt to current rustc (closes #381)

### LINKED ISSUE #381: hyper doesn't built with new rustc.
`IpAddr` was splitted to `Ipv4Addr` and `Ipv6Addr`

```
src\server/mod.rs:4:16: 4:22 error: unresolved import `std::net::IpAddr`. There is no `IpAddr` in `std::net`
src\server/mod.rs:4 use std::net::{IpAddr, SocketAddr};
```

rustc 1.0.0-dev (c10918905 2015-03-18) (built 2015-03-18)

### PR DESCRIPTION
**Pull request by adrianheine**
closes #381.

### CODE REVIEW

**Comment by GitCop** [comment]
Thanks for contributing! Unfortunately, I'm here to tell you there were the following style issues with your Pull Request:

 * Commit: 1b69c8404dc884dad5d37bb81e7fbcec7855602c
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**
  * Invalid type. Valid types are **feat, fix, docs, style, refactor, perf, test, chore, revert**

Guidelines are available at https://github.com/hyperium/hyper/blob/master/CONTRIBUTING.md

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
Thanks for contributing! Unfortunately, I'm here to tell you there were the following style issues with your Pull Request:

 * Commit: 72313b28090f8148c31b0f43c308f26ca4dd3079
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/hyperium/hyper/blob/master/CONTRIBUTING.md

---
This message was auto-generated by https://gitcop.com

**Comment by adrianheine** [comment]
Travis is on 2015-03-14 and thus fails.

**Comment by Ryman** [comment]
Shouldn't this be using http://doc.rust-lang.org/std/net/enum.SocketAddr.html?

**Comment by pyfisch** [comment]
@Ryman I also think it should be `SocketAddr`. Since we always use both host and port, we can replace the ip, port pair with a socket address.

**Comment by seanmonstar** [comment]
It seems the removal of `std::net::IpAddr` was a mistake, and they're adding it back in...

**Comment by adrianheine** [comment]
Using `SocketAddr` seems reasonable to me.

**Pull request merged**
