### PR TITLE
feat(h2): add read body timeout

### PR DESCRIPTION
**Pull request by silence-coding**

### CODE REVIEW

**Comment by silence-coding** [comment]
Fix https://github.com/hyperium/hyper/issues/2864

**Comment by silence-coding** [comment]
I'm hesitant to provide uniform configuration in hyper server builder, like http1_header_read_timeout.

**Comment by seanmonstar** [comment]
As discussed in #2864, I don't believe we need to have this in hyper.

**Comment by lidong14** [comment]
@seanmonstar I think this is necessary, because as an HTTP framework, body timeout is a basic capability. like  tomcat , jetty.

**Comment by silence-coding** [comment]
> As discussed in #2864, I don't believe we need to have this in hyper.

When hyper is used as the proxy, req.body_mut().data().await is not applicable.

**Comment by seanmonstar** [comment]
> as an HTTP framework, body timeout is a basic capability

Sure, I agree it is necessary to be able to set some sort of timeout. But since it's possible and easy to do outside of hyper, I don't believe it belongs *in* hyper. A util would be fine.

> When hyper is used as the proxy, req.body_mut().data().await is not applicable.

A body adapter could be written. Some sort of `impl HttpBody for TimeoutPerBuf<impl HttpBody>`.

**Comment by silence-coding** [comment]
-> A body adapter could be written. Some sort of impl HttpBody for TimeoutPerBuf<impl HttpBody>.
This is a good idea. I think it can be out of hyper, but it should be in the ecosystem provided by hyper. Can more security-related features be added to version 1.0, such as idle connection timeout, read/write timeout, and others?

**Comment by seanmonstar** [comment]
> but it should be in the ecosystem provided by hyper

It could be a fair candidate for the eventual `hyper-util` crate!

> Can more security-related features be added to version 1.0

The general answer is yes, but I'd recommend opening an issue to discuss any proposed feature. At the same time, if it's something that can reasonably be implemented *outside* of hyper, then it probably should stay external.

I'm going to close this based on previous discussion.

**Pull request closed without merging**
