### PR TITLE
Update `Client::configure` example to compile.

### PR DESCRIPTION
**Pull request by frewsxcv**

### CODE REVIEW

**Comment by GitCop** [comment]
Thanks for contributing! Unfortunately, I'm here to tell you there were the following style issues with your Pull Request:

 * Commit: 4d4857d84ac006c057c11c1ff9c3ec4891a44358
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/hyperium/hyper/blob/master/CONTRIBUTING.md

---
This message was auto-generated by https://gitcop.com

**Comment by seanmonstar** [comment]
Ah, how irritating that I used the wrong tag to mark it as no_run. Thanks for catching that! Seems this fix though doesn't fully fix it? I'm guessing that since this now has an `extern crate`, it needs a `fn main() {}` and `extern crate hyper;` and all the shebang.

**Comment by GitCop** [comment]
Thanks for contributing! Unfortunately, I'm here to tell you there were the following style issues with your Pull Request:

 * Commit: ff6a3d22a427a92c20363000a3370b84bf1eca9f
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/hyperium/hyper/blob/master/CONTRIBUTING.md

---
This message was auto-generated by https://gitcop.com

**Comment by seanmonstar** [comment]
Thanks!

**Pull request merged**
