### PR TITLE
refactor: Use async/await in HttpConnector

### LINKED ISSUE #1984: Rewrite HttpConnector internals with async/await
The internal code handling the `HttpConnector` is messy from manual future implementations. I believe it could be much cleaner if written with `async fn` and `await`.

### PR DESCRIPTION
**Pull request by Marwes**
Closes #1984

### CODE REVIEW

**Comment by seanmonstar** [comment]
This is excellent work! I really need to get rustfmt running by default so it doesn't make diffs harder to read...

**Comment by Marwes** [comment]
Ah :( seems like my format on save setup does not obey `.rustfmt.toml` anymore, pretty sure it used to...

gitcop doesn't explain which or why the commit messages are invalid so I am not sure what to do about it

**Comment by seanmonstar** [comment]
Sorry I didn't get back to this sooner (I've been trying to get all the things released), and so merging the Tokio 0.2 upgrade has caused merge conflicts.

**Comment by seanmonstar** [comment]
Thanks so much!

**Pull request merged**
