### PR TITLE
feat(headers): support WWW-Authenticate

### PR DESCRIPTION
**Pull request by KeenS**
- [x] The commit messages match the guidelines in https://github.com/hyperium/hyper/blob/master/CONTRIBUTING.md#git-commit-guidelines

This PR a part of #773. Though the issue suggests more features, I'm motivated only on WWW-Authenticate and only implements WWW-Authenticate in this PR.

 I'll implement `WWW-Authenticate` header described in [RFC 7235](https://tools.ietf.org/html/rfc7235), Basic Challenge described in [RFC 7617](https://tools.ietf.org/html/rfc7617) and Digest Challenge described in [RFC 7616](https://tools.ietf.org/html/rfc7616). 

Questions
* I'm submitting this PR to `0.10.x` branch. Is this correct?
* Because I'm not a native English speaker(writer), I feel hard to write documents. Would anyone help me writing documents or write documents after this PR is merged?

TODO:
* [x] accept multiple headers
* [x] consult the definition of quoted string and implement correctly
* [x] more APIs like `get_raw`
* [x] write documents

### CODE REVIEW

**Comment by GitCop** [comment]
Thanks for contributing! Unfortunately, I'm here to tell you there were the following style issues with your Pull Request:

 * Commit: c9bf0437c6662d92ce86c4f4e56981117a8dceeb
  * Invalid type. Valid types are **feat, fix, docs, style, refactor, perf, test, chore, revert**

Guidelines are available at https://github.com/hyperium/hyper/blob/master/CONTRIBUTING.md

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
Thanks for contributing! Unfortunately, I'm here to tell you there were the following style issues with your Pull Request:

 * Commit: db572ad339a83fbf2d51fa1bd6a729659a0bb0d8
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/hyperium/hyper/blob/master/CONTRIBUTING.md

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
Thanks for contributing! Unfortunately, I'm here to tell you there were the following style issues with your Pull Request:

 * Commit: db572ad339a83fbf2d51fa1bd6a729659a0bb0d8
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: dd847c3bbe727bd0146bdcc2bfb2fe4b06f82888
  * Invalid type. Valid types are **feat, fix, docs, style, refactor, perf, test, chore, revert**

Guidelines are available at https://github.com/hyperium/hyper/blob/master/CONTRIBUTING.md

---
This message was auto-generated by https://gitcop.com

**Comment by KeenS** [comment]
rebased to fix commit messages

**Comment by seanmonstar** [comment]
Um, wow! This is a lot of work!

I haven't reviewed the code yet, but curious, being so much, does it make sense as possibly a separate crate?

**Comment by KeenS** [comment]
Yes it does. Though it depends on some internal types like `CowStr`, if only I ported with them, it can be separated.

**Comment by KeenS** [comment]
@seanmonstar Are you going to merge this patch, or want it to be a separated crate?
This is NOT a authorization framework but just a header parser/printer. I implemented this because 401 unauthorized requires for the response to contain WWW-Authenticate header.

**Comment by seanmonstar** [comment]
I'm currently sitting somewhere in the middle. I don't feel like this doesn't belong, but I also feel apprehensive about the surface area being added. If through usage, it's found that changes are needed, it'd be a breaking version bump for everyone who uses hyper.

What if this were released as a different crate, and after usage has found if any changes are required, then it can be considered for including in here? Does that sound reasonable?

**Comment by KeenS** [comment]
Yes, that's very reasonable. Then I close this PR and prepare for publishing it as a new crate. Thank you.

**Comment by fdubois1** [comment]
Where did you publish that finally ?  You talked about a new crate, I red somewhere hyper-auth but can't find it.

**Comment by KeenS** [comment]
this https://crates.io/crates/www-authenticate

**Comment by fdubois1** [comment]
Thank you @KeenS

**Comment by KeenS** [comment]
:)

**Pull request closed without merging**
