### PR TITLE
docs(server): Add a forms server example

### PR DESCRIPTION
**Pull request by jolhoeft**
Add an example program illustrating parsing a request body through
generating a response body.

### CODE REVIEW

**Comment by jolhoeft** [comment]
The AppVeyor failures don't appear to be related to this PR

**Comment by seanmonstar** [comment]
Hey neat! Do you think this sort of thing would be well suited to be a [guide](https://hyper.rs/guides/)?

**Comment by jolhoeft** [comment]
Possibly. I wrote it because I realized I was misunderstanding how to get the response body out of the request body. I was thinking of it as a series of transforms on the request body until I had the response body, but couldn't figure out how to bail early with an error status if I needed to. I eventually realized you transform the request body into a response future. You create a new future/stream for the response body.

Having written that, it does sound like a very useful thing for the guide.

**Comment by seanmonstar** [comment]
Yea, that's a good point. You tell me, would you be interested in turning this into a guide at https://github.com/hyperium/hyperium.github.io/tree/master/_guides/server?

**Comment by jolhoeft** [comment]
I will give it a try. I expect it will take me a couple days. Clear prose is harder to write than code.

Do you want to merge this in separate from that? I see the example and the guide as two different but related things.

**Comment by seanmonstar** [comment]
My personal (somewhat weakly held) opinion so far has been that "examples" can be hard to understand without context, and I've tried to not add too many, but instead any time I've wanted to make an example, tried to make it a guide instead.

**Comment by jolhoeft** [comment]
Oddly my experience is the reverse. I look for examples before a detailed guide. I find a good example can give me a better high level view of how everything goes together. People have a wide range of learning styles, though, and I think we need both.

My approach on the guide is to explain this example in more detail, and add comments on how to approach Json processing, and possibly spawning threads for generating response bodies.

**Comment by seanmonstar** [comment]
Fair enough, convinced! Thanks!

**Pull request merged**
