### PR TITLE
Prevent a panic if the channel used by Body is terminated

### PR DESCRIPTION
**Pull request by meh**
I don't know if this is the right way, but I got a panic during `Drop`, and this makes it werk.

### CODE REVIEW

**Comment by seanmonstar** [comment]
Thanks for the PR! What was the panic, and why did it happen during `Drop`? I'd like to better understand, since without knowing, this looks like potentially an extra method check on every iteration.

**Comment by meh** [comment]
last

This is the stack trace I got (I also posted this on the Discord, I'm also there if you wanna ping me), it was happening after everything was done in the code, so during the `Drop`ping of stuff.

At fault might also be `rusoto_s3`, but I'm not sure if it's `rusoto_s3` using the `Body` wrong, or if it's the `Body` that is doing something wrong.

Definitely a weird edge case.

**Comment by seanmonstar** [comment]
Interesting stack trace... It seems the panic is from polling for another chunk after a previous poll already returned `Poll::Ready(None)`. The code in `Body` doesn't poll it extra times, so it seems that at some level above, something is polling the body after it "finished". I'd lean towards the bug being up there, and not something to fix in hyper itself.

**Comment by meh** [comment]
Suspected so, I will look into fixing it from the rusoto side, will link the PR/issue here once it's up.

**Comment by seanmonstar** [comment]
For now, I'm going to close this. Curious how it ends, though!

**Pull request closed without merging**
