### PR TITLE
address tokio_service mutability changes

### LINKED ISSUE #993: tokio branch does not compile after tokio_service mutability change
i am gonna try to write a PR to fix this! here's the error for posterity.

```
error[E0053]: method `call` has an incompatible type for trait
  --> src/client/connect.rs:81:5
   |
81 |     fn call(&mut self, url: Url) -> Self::Future {
   |     ^ types differ in mutability
   |
   = note: expected type `fn(&client::connect::HttpConnector, url::Url) -> client::connect::HttpConnecting`
   = note:    found type `fn(&mut client::connect::HttpConnector, url::Url) -> client::connect::HttpConnecting`

error[E0053]: method `call` has an incompatible type for trait
   --> src/client/connect.rs:133:5
    |
133 |     fn call(&mut self, url: Url) -> Self::Future {
    |     ^ types differ in mutability
    |
    = note: expected type `fn(&client::connect::HttpsConnector, url::Url) -> client::connect::HttpsConnecting`
    = note:    found type `fn(&mut client::connect::HttpsConnector, url::Url) -> client::connect::HttpsConnecting`

error[E0053]: method `call` has an incompatible type for trait
   --> src/client/mod.rs:121:5
    |
121 |     fn call(&mut self, req: Request) -> Self::Future {
    |     ^ types differ in mutability
    |
    = note: expected type `fn(&client::Client<C>, client::request::Request) -> client::FutureResponse`
    = note:    found type `fn(&mut client::Client<C>, client::request::Request) -> client::FutureResponse`

error[E0053]: method `call` has an incompatible type for trait
   --> src/server/mod.rs:270:5
    |
270 |       fn call(&mut self, message: Self::Request) -> Self::Future {
    |  _____^ starting here...
271 | |         let (head, body) = match message {
272 | |             Message::WithoutBody(head) => (head, http::Body::empty()),
273 | |             Message::WithBody(head, body) => (head, body.into()),
274 | |         };
275 | |         let req = request::new(self.remote_addr, head, body);
276 | |         self.inner.call(req).map(map_response_to_message)
277 | |     }
    | |_____^ ...ending here: types differ in mutability
    |
    = note: expected type `fn(&server::HttpService<T>, tokio_proto::streaming::Message<http::MessageHead<http::RequestLine>, tokio_proto::streaming::Body<http::chunk::Chunk, error::Error>>) -> futures::Map<<T as tokio_service::Service>::Future, fn(server::response::Response) -> tokio_proto::streaming::Message<http::MessageHead<status::StatusCode>, tokio_proto::streaming::Body<http::chunk::Chunk, error::Error>>>`
    = note:    found type `fn(&mut server::HttpService<T>, tokio_proto::streaming::Message<http::MessageHead<http::RequestLine>, tokio_proto::streaming::Body<http::chunk::Chunk, error::Error>>) -> futures::Map<<T as tokio_service::Service>::Future, fn(server::response::Response) -> tokio_proto::streaming::Message<http::MessageHead<status::StatusCode>, tokio_proto::streaming::Body<http::chunk::Chunk, error::Error>>>`

error: aborting due to 4 previous errors

error: Could not compile `hyper`.

Caused by:
  process didn't exit successfully: `rustc --crate-name hyper src/lib.rs --crate-type lib -g --cfg feature="default" -C metadata=d4a40b29437ca96f -C extra-filename=-d4a40b29437ca96f --out-dir /Users/ag_dubs/rust/hyper/target/debug/deps --emit=dep-info,link -L dependency=/Users/ag_dubs/rust/hyper/target/debug/deps --extern tokio_tls=/Users/ag_dubs/rust/hyper/target/debug/deps/libtokio_tls-f3e5968fda14b2c3.rlib --extern httparse=/Users/ag_dubs/rust/hyper/target/debug/deps/libhttparse-996fc9116d9dcf83.rlib --extern url=/Users/ag_dubs/rust/hyper/target/debug/deps/liburl-8aa0752fa6071745.rlib --extern vecio=/Users/ag_dubs/rust/hyper/target/debug/deps/libvecio-b90c1aba84926426.rlib --extern mime=/Users/ag_dubs/rust/hyper/target/debug/deps/libmime-c64500266507952e.rlib --extern tokio_core=/Users/ag_dubs/rust/hyper/target/debug/deps/libtokio_core-a0dfb4e4436a27df.rlib --extern unicase=/Users/ag_dubs/rust/hyper/target/debug/deps/libunicase-ceb43341bcf99e15.rlib --extern native_tls=/Users/ag_dubs/rust/hyper/target/debug/deps/libnative_tls-2758c2463fafa3da.rlib --extern time=/Users/ag_dubs/rust/hyper/target/debug/deps/libtime-02018c58facc89ee.rlib --extern tokio_service=/Users/ag_dubs/rust/hyper/target/debug/deps/libtokio_service-94bffe2000aad1d6.rlib --extern futures_cpupool=/Users/ag_dubs/rust/hyper/target/debug/deps/libfutures_cpupool-0057d211711ed4da.rlib --extern rustc_serialize=/Users/ag_dubs/rust/hyper/target/debug/deps/librustc_serialize-03b62901d97343ea.rlib --extern language_tags=/Users/ag_dubs/rust/hyper/target/debug/deps/liblanguage_tags-69c1ab0d09b59b1d.rlib --extern log=/Users/ag_dubs/rust/hyper/target/debug/deps/liblog-1ce22d3a92f37841.rlib --extern cookie=/Users/ag_dubs/rust/hyper/target/debug/deps/libcookie-a1e4ecdfdab40c7f.rlib --extern tokio_proto=/Users/ag_dubs/rust/hyper/target/debug/deps/libtokio_proto-872bc602f52ffd09.rlib --extern relay=/Users/ag_dubs/rust/hyper/target/debug/deps/librelay-3c2ac943d6a43c65.rlib --extern mio=/Users/ag_dubs/rust/hyper/target/debug/deps/libmio-9b8eb2d3b7c024fa.rlib --extern futures=/Users/ag_dubs/rust/hyper/target/debug/deps/libfutures-986bba8c0d767260.rlib` (exit code: 101)
```

### PR DESCRIPTION
**Pull request by ashleygwilliams**
ideally eventually fixes #993

### CODE REVIEW

**Comment by ashleygwilliams** [comment]
current status:

```
  Compiling hyper v0.10.0-a.0 (file:///Users/ag_dubs/rust/hyper)
error: cannot borrow immutable field `self.pool` as mutable
   --> src/client/mod.rs:140:24
    |
140 |         let checkout = self.pool.checkout(&url[..::url::Position::BeforePath]);
    |                        ^^^^^^^^^

error: cannot borrow immutable field `self.connector` as mutable
   --> src/client/mod.rs:145:13
    |
145 |             self.connector.connect(url)
    |             ^^^^^^^^^^^^^^

error: aborting due to 2 previous errors

Build failed, waiting for other jobs to finish...
error: cannot borrow immutable field `self.pool` as mutable
   --> src/client/mod.rs:140:24
    |
140 |         let checkout = self.pool.checkout(&url[..::url::Position::BeforePath]);
    |                        ^^^^^^^^^

error: cannot borrow immutable field `self.connector` as mutable
   --> src/client/mod.rs:145:13
    |
145 |             self.connector.connect(url)
    |             ^^^^^^^^^^^^^^

error: aborting due to 2 previous errors

error: Could not compile `hyper`.
```

**Comment by markuskobler** [comment]
Might be worth looking at #992

**Comment by seanmonstar** [comment]
I believe the last change would be to adjust the `Connect` trait, so that `Connect::connect` takes &self as well.

**Comment by seanmonstar** [comment]
Wonderful! I'll click merge after travis finishes.

Closes #992 
Closes #993

**Comment by Ms2ger** [comment]
Note that the "Closes #NNNN" syntax only works in commit messages and PR summaries, not comments.

**Comment by seanmonstar** [comment]
Well that's stupid.

**Pull request merged**
