### PR TITLE
Clippy fixes with markdown docs

### PR DESCRIPTION
**Pull request by Manishearth**

### CODE REVIEW

**Comment by GitCop** [comment]
Thanks for contributing! Unfortunately, I'm here to tell you there were the following style issues with your Pull Request:

 * Commit: 581e01e685d1464b4bcaef8c11a76cb63e1381b0
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/hyperium/hyper/blob/master/CONTRIBUTING.md

---
This message was auto-generated by https://gitcop.com

**Comment by seanmonstar** [comment]
Seems the change to the Box::new doesn't work.

**Comment by Manishearth** [comment]
My bad, forgot to undo it properly. fixed

**Comment by seanmonstar** [comment]
Thanks!

**Pull request merged**
