### PR TITLE
docs(examples): Update web_api example to use async await

### PR DESCRIPTION
**Pull request by messense**
Ref #1849

### CODE REVIEW

**Comment by messense** [comment]
This does not compile yet, error:

```
error[E0495]: cannot infer an appropriate lifetime for borrow expression due to conflicting requirements
   --> examples/web_api.rs:118:40
    |
118 |                 response_examples(req, &client)
    |                                        ^^^^^^^
    |
note: first, the lifetime cannot outlive the lifetime '_ as defined on the body at 117:46...
   --> examples/web_api.rs:117:46
    |
117 |             Ok::<_, GenericError>(service_fn(move |req| {
    |                                              ^^^^^^^^^^
note: ...so that closure can access `client`
   --> examples/web_api.rs:118:40
    |
118 |                 response_examples(req, &client)
    |                                        ^^^^^^^
note: but, the lifetime must be valid for the expression at 117:35...
   --> examples/web_api.rs:117:35
    |
117 |             Ok::<_, GenericError>(service_fn(move |req| {
    |                                   ^^^^^^^^^^
note: ...so type `fn([closure@examples/web_api.rs:117:46: 119:14 client:hyper::Client<hyper::client::HttpConnector>]) -> hyper::service::service::ServiceFn<[closure@examples/web_api.rs:117:46: 119:14 client:hyper::Client<hyper::client::HttpConnector>], hyper::Body> {hyper::service::service_fn::<[closure@examples/web_api.rs:117:46: 119:14 client:hyper::Client<hyper::client::HttpConnector>], hyper::Body, impl std::future::Future>}` of expression is valid during the expression
   --> examples/web_api.rs:117:35
    |
117 |             Ok::<_, GenericError>(service_fn(move |req| {
    |                                   ^^^^^^^^^^

error: aborting due to previous error

error: Could not compile `hyper`.
```

Not sure how to fix it.

**Comment by seanmonstar** [comment]
I *think* it's complaining that the future returned in `service_fn` has a borrow on `&client`, but the `service_fn` closure owns `client`. So, if the `service_fn` were dropped after return a future but before that future started, the borrow would be invalid.

It's holding a borrow because any references passed to an `async fn` are held for the duration of the returned future.

You could either pass in clones of the client, or change the `async fn`s to be normal functions, and use an internal `async` block. Like:

```rust
let fut = client.request(req);
async move {
    let res = fut.await?;
}
```

**Comment by weihanglo** [comment]
@messense 
The lifetime issue was fixed on #1872. Just clone the client again as @seanmonstar said.

**Comment by messense** [comment]
Closing in favor of #1872

**Pull request closed without merging**
