### PR TITLE
Issue 351: default trait for client

### PR DESCRIPTION
**Pull request by winding-lines**
Sean, nice meeting you at the launch meetup today!

I am not sure what you are looking for in issue #351, here is a first minimal attempt. Comments welcome :)

### CODE REVIEW

**Comment by GitCop** [comment]
Thanks for contributing! Unfortunately, I'm here to tell you there were the following style issues with your Pull Request:

 * Commit: b4f8ec489f6ecdba68e189ffc8bfdf95d78745dc
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/hyperium/hyper/blob/master/CONTRIBUTING.md

---
This message was auto-generated by https://gitcop.com

**Comment by seanmonstar** [comment]
Yes, this seems like a reasonable default to me.

**Comment by winding-lines** [comment]
Thanks Sean! Which other traits would work for Client? Do Copy/Send/Sync make sense?

**Comment by seanmonstar** [comment]
Client can't be `Copy`: it has a `Box<NetworkConnector>`, are `Box<T>` is not Copy. Send and Sync aren't implemented like most traits.

**Comment by winding-lines** [comment]
Thanks, do you want to close this issue then?

**Comment by seanmonstar** [comment]
This is a pull request, it's already been merged :)

**Pull request merged**
