### PR TITLE
feat(headers): add Content-Location header

### LINKED ISSUE #870: Add Content-Location header
See https://tools.ietf.org/html/rfc7231#section-3.1.4.2

### PR DESCRIPTION
**Pull request by koivunej**
Closes #870

### CODE REVIEW

**Comment by koivunej** [comment]
looking at some previous header adding PRs I might've gone too far by adding this into `literal!{ ... }` in `src/header/mod.rs`.

should I remove it?

**Comment by seanmonstar** [comment]
@koivunej the `literal!` stuff is for particularly common headers. Is `Content-Location` that common?

**Comment by koivunej** [comment]
@seanmonstar I do not think it is, I'll remove it from `literals!`.

**Comment by seanmonstar** [comment]
Great, thanks!

**Pull request merged**
