### PR TITLE
docs(*): add details for hello world example

### LINKED ISSUE #1265: Hello World Example cargo.toml ?
The hyper hello world example is [a .rs file](https://github.com/hyperium/hyper/blob/master/examples/hello.rs).

Shouldn't it comes with a cargo.toml file so that we can know its dependencies? Just tried that example however service_fn cannot be found in crates.io

### PR DESCRIPTION
**Pull request by mrenoon**
Add instructions for a quick set-up of a stand-alone hello world hyper server.
Closes #1265

- [ ] The commit messages match the guidelines in https://github.com/hyperium/hyper/blob/master/CONTRIBUTING.md#git-commit-guidelines

### CODE REVIEW

**Comment by seanmonstar** [comment]
Thanks for submitting the PR!

I'm curious, was it difficult to understand how the example worked without instructions like these? Or without seeing https://hyper.rs/guides?

**Comment by mrenoon** [comment]
I had no problems with the example. However, there are some people who read our README, see the line "See the Hello World example for a toy server using hyper.", clicked to see the file and do not immediately know how to get it running, as evidenced by issue #1265

**Comment by seanmonstar** [comment]
Hm, sure. It probably makes most sense then to just have the README link to self-contained example in the guides.

**Comment by seanmonstar** [comment]
The README has been updated by removing that line, and emphasizing looking at the guides instead. Ideally, there is only 1 place that needs to be kept up-to-date. Thanks for writing this up, though!

**Comment by mrenoon** [comment]
Ok cool!

**Pull request closed without merging**
