### PR TITLE
feat(headers): Add Referrer-Policy header

### PR DESCRIPTION
**Pull request by aravind-pg**
Required to implement [referrer policy delivery by header](https://www.w3.org/TR/referrer-policy/#referrer-policy-header) in Servo (see servo/servo#11860).

(See #850 for previous discussion. This is just the 0.9.x version.)

### CODE REVIEW

**Comment by aravind-pg** [comment]
@seanmonstar Could you please bump the version?

**Comment by aravind-pg** [comment]
@seanmonstar Ping, Servo needs the version bump.

**Comment by seanmonstar** [comment]
Woops! Good news is that the wait means 0.9.10 also includes the `Origin` header. Published!

**Comment by aravind-pg** [comment]
Great, thanks!

**Pull request merged**
