### PR TITLE
Rename body to recv temporarily

### PR DESCRIPTION
**Pull request by Michael-J-Ward**
Resolves https://github.com/hyperium/hyper/issues/2963

This currently branches off of https://github.com/hyperium/hyper/pull/2961

### CODE REVIEW

**Comment by seanmonstar** [comment]
How easy would it be to separate it from the other PR? I suspect this one could merge faster.

**Comment by Michael-J-Ward** [comment]
I did pop off the commit, I also rebased off of master.

on master, this is failing to compile and test.
`RUSTFLAGS='--cfg hyper_unstable_ffi' cargo test --all-features --all`

**Comment by Michael-J-Ward** [comment]
(forgot to apply `cargo fmt`, apologies)

**Comment by seanmonstar** [comment]
Looks like the last piece remaining is to remove the link to `Body` in the documentation. We'll have a docs pass later on.

**Review by seanmonstar — APPROVED** [review]
Awesome, thank you!

**Pull request merged**
