### PR TITLE
fix(h2): add http2_max_header_list_size to hyper::server::Builder

### PR DESCRIPTION
**Pull request by jiahaoliang**
fix incomplete changes introduced from #2828

### CODE REVIEW

**Comment by jiahaoliang** [comment]
Hi @seanmonstar, as discussion in #2828 , add http2_max_header_list_size to hyper::server::Builder to expose the API.

Please review, thanks.

**Review by seanmonstar — APPROVED** [review]

**Comment by jiahaoliang** [comment]
@seanmonstar Hi Sean, I don’t understand how this change failed Miri test. How may I pass it? Thanks.

**Comment by jiahaoliang** [comment]
@seanmonstar Hi Sean, sorry to bother you again. How may I get through the Miri test for this PR?

**Comment by seanmonstar** [comment]
I restarted the Miri check, and it worked. It seems there was an issue in Miri for a little while that they reverted.

**Pull request merged**
