### PR TITLE
Fixed the build with the latest rust-nightly.

### PR DESCRIPTION
**Pull request by stchris**
(rustc 1.0.0-nightly (92ff8ea52 2015-01-27 23:08:13 +0000))

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: afa8a1b314640b1e5d98d0d343aaa187153dc34c
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/hyperium/hyper/blob/master/CONTRIBUTING.md

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: f1523324c8dc45b859353c6b9d1498aa1771f68f
  * Your commit message body contains a line that is longer than 100 characters

Guidelines are available at https://github.com/hyperium/hyper/blob/master/CONTRIBUTING.md

---
This message was auto-generated by https://gitcop.com

**Comment by seanmonstar** [comment]
:+1:

**Comment by seanmonstar** [comment]
Er, looks like travis is finding problems.

**Comment by stchris** [comment]
Yes, I only fixed the build. Not sure how to fix the tests, though :(

**Comment by seanmonstar** [comment]
No problem, I'll pull your commit and fix the rest.

**Comment by stchris** [comment]
Cheers! :+1:

**Comment by seanmonstar** [comment]
Filed all the fixes in #287 . Thanks!

**Pull request closed without merging**
