### PR TITLE
fix(rustup): added docs for associated types

### PR DESCRIPTION
**Pull request by Byron**
This requirement was added recently.
See https://github.com/rust-lang/rust/issues/20648

### CODE REVIEW

**Comment by seanmonstar** [comment]
Thanks, but this was fixed in #340 .

**Comment by Byron** [comment]
:D ! I didn't scroll down in the diff and missed the important part.
Funny - maybe next time, I'll be first.

**Comment by Byron** [comment]
Besides, would it be possible for you to publish a new release ? I am suffering from [this bug](https://github.com/rust-lang/cargo/issues/1215) :(.
Thank you

**Comment by seanmonstar** [comment]
I just published 0.2.1 :)

**Pull request closed without merging**
