### PR TITLE
Fixes compilation errors with latest rust

### PR DESCRIPTION
**Pull request by AaronM04**

### CODE REVIEW

**Comment by GitCop** [comment]
Thanks for contributing! Unfortunately, I'm here to tell you there were the following style issues with your Pull Request:

 * Commit: 3bb03749797747067c83f3f7175e7f82b76125f2
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/hyperium/hyper/blob/master/CONTRIBUTING.md

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
Thanks for contributing! Unfortunately, I'm here to tell you there were the following style issues with your Pull Request:

 * Commit: c1f80e0d7e4568dd382e580a129aff9426581c71
  * Invalid type. Valid types are **feat, fix, docs, style, refactor, perf, test, chore, revert**

Guidelines are available at https://github.com/hyperium/hyper/blob/master/CONTRIBUTING.md

---
This message was auto-generated by https://gitcop.com

**Comment by AaronM04** [comment]
Yay, GitCop approves :)

**Comment by seanmonstar** [comment]
I'd have put "docs(readme)" myself :)

**Comment by AaronM04** [comment]
Ah, of course. That makes more sense.

**Pull request merged**
