### PR TITLE
remove dependency on `tracing`'s `log` feature

### LINKED ISSUE #2326: Remove log feature of tracing
The `log` feature of `tracing` should not be enabled by default in hyper (or h2). Since people likely are depending on the `log` records, this is a breaking change, and should be done in 0.14 (with a note in the release notes).

### PR DESCRIPTION
**Pull request by mikeyhew**
fixes #2326

I wasn't sure what the right way to update the changelog was, so I just used my best guess. Let me know if I should do something differently.

### CODE REVIEW

**Comment by mikeyhew** [comment]
how do I see the gitcop error message? The link just goes to https://gitcop.com/

**Comment by seanmonstar** [comment]
Thanks! You can leave the changelog update out, those are automatically construct with a script at release time.

**Comment by mikeyhew** [comment]
OK, I've removed the changelog update.

**Comment by seanmonstar** [comment]
Thanks!

**Pull request merged**
