### PR TITLE
Add 'take_buf' method to BufReader.

### PR DESCRIPTION
**Pull request by SergioBenitez**
Hello!

I'm using the latest 0.9.x release on a project I'm working on, and I'm quite in need of this method. As I'd like to release my project on crates.io soon, I was hoping you would merge this in and then release a new version of hyper 0.9.x on crates.io. I understand that 0.9.x has effectively been abandoned in favor of 0.10, so I hope it won't be too much trouble.

Thanks!
Sergio

### CODE REVIEW

**Comment by SergioBenitez** [comment]
Note that the Travis-CI failure is unrelated to my PR.

**Comment by SergioBenitez** [comment]
@seanmonstar ping.

**Comment by seanmonstar** [comment]
This actually worries me a little. What happens if you take the buf and then try to keep on reading on the `Request`? It's internal counter of whether it can keep-alive will be all ruined, won't it?

**Comment by SergioBenitez** [comment]
@seanmonstar Everything works as expected: the buffer will be refilled, and reading will continue. I explicitly tested that keep-alive continues working as expected.

**Comment by seanmonstar** [comment]
Reading through the code, it looks like `HttpReader` wraps `BufReader`s, so the `SizedReader` (and `Chunked`) will not have counted how many bytes have been read off the socket, only how many have been read from the buffer.

What depends on this?

**Comment by SergioBenitez** [comment]
That's right, but the original `Reader` shouldn't be used after calling `take_buf`. Even then, in the worst case, the `SizedReader` will simply say that there was an `eof`.

In a soon-to-be released project, I keep the TCP stream around for later reading. The current API forces me to keep around two lifetimes if I want to keep the TCP stream around, neither of which are necessary. With this API, I don't need to keep any lifetimes around, and I can rewrap the stream in more friendly APIs.

**Comment by SergioBenitez** [comment]
Hi @seanmonstar, still waiting on this. With very high probability, I'll be publishing my crate next week, and I'd really like to not have a fork of Hyper in crates.io. Let me know. If it helps with getting this out, I'd be happy to add a `#[doc(hidden)]` tag so that others don't use this unnecessarily.

**Comment by SergioBenitez** [comment]
@seanmonstar Can we get a new release with this change?

**Comment by seanmonstar** [comment]
I published 0.9.14 a few days ago that included this.

**Pull request merged**
