### PR TITLE
fix(http): Consume entire chunked encoding message

### PR DESCRIPTION
**Pull request by sfackler**
The trailing newline otherwise breaks keepalive after a chunked request.

- [X] The commit messages match the guidelines in https://github.com/hyperium/hyper/blob/master/CONTRIBUTING.md#git-commit-guidelines

### CODE REVIEW

**Comment by sfackler** [comment]
I think this is also a problem on the tokio version.

**Comment by seanmonstar** [comment]
I haven't built a test yet for master, but the chunked decoder got a pretty extensive rewrite to handle reads blocking mid chunk-size, so it may have been dealt with after all.

Either way, thanks for this!

**Comment by sfackler** [comment]
Thanks! Could you cut an 0.10 release with this when you have a chance?

**Comment by seanmonstar** [comment]
Published in 0.10.5.

**Comment by jwilm** [comment]
re: tokio

I contributed a [similar fix](https://github.com/hyperium/hyper/commit/bffde8c841353e05e9aea267ca94848ccdeeb394) for this on master (rotor) at some point before tokio was released. Not sure if it was before or after the decoder rewrite or how many of those fixes actually made it into the tokio tree.

**Pull request merged**
