### PR TITLE
Guarantee file unchanged!

### PR DESCRIPTION
**Pull request by passchaos**

### CODE REVIEW

**Comment by sfackler** [comment]
What is this protecting against?

**Comment by sfackler** [comment]
Oh, nevermind. I see.

It seems really bad that this is reading 16 bytes at a time. That buffer should be like 1000 times larger than it is.

**Comment by jolhoeft** [comment]
The small buffer is deliberate since the test file is so small. There is a comment about that, but further up the file.

**Comment by passchaos** [comment]
Yeah, the buffer is too small to get a fast download speed, but more importly, the bound is necessary to get the consistent file.

**Comment by passchaos** [comment]
In most cases, the size of the file is not a multiple of that of the 16, so, the last time to read a file to the buffer will not fill the buffer, without boundary, send files will be compared to the original file more than a few bytes.

**Comment by jolhoeft** [comment]
Ok, I tested, and you are right, we are getting trailing data, but the browser is ignoring them. I was confusing it with a Vec.

**Comment by seanmonstar** [comment]
Thanks!

**Pull request merged**
