### PR TITLE
Added basic azure pipelines configuration

### PR DESCRIPTION
**Pull request by Perseus101**
References #1673 

I've added a fairly basic azure pipelines configuration that tests stable on windows, and mac, and tests stable, beta, and nightly on linux.

I ran a manual build in a test azure project and there were 2 failures:
* linux-nightly: Looks like a trivial fix. Just some deprecation warnings.
* windows: 2 tests hung. I'm not sure what the cause was exactly, I'm going to do some more investigating. The failing test were:
    * http2_body_user_error_sends_reset_reason
    * http2_service_error_sends_reset_reason

### CODE REVIEW

**Comment by Perseus101** [comment]
Forgive my ignorance, it's my first time contributing here. I wasn't really sure what "scope" to throw this under, so I picked "headers" because it was first on the list in the contribution guidelines. Let me know what I should change it to.

**Comment by LucioFranco** [comment]
Hi! This looks like a good start! Im just gonna drop a link to https://github.com/tokio-rs/tokio as we have been using azure there and are pretty happy so maybe there are things you can pull from there as well!

**Comment by ahmedcharles** [comment]
`chore(ci)` seems better than `chore(headers)` given that the list in the contribution guidelines is just of examples.

I suspect that rebasing will fix the travis nightly failure.

**Comment by Perseus101** [comment]
@ahmedcharles Thanks for the recommendation, rebasing fixed the test failures.

I've added some small azure pipelines templates, following the example of the tokio repository (Thanks @LucioFranco!). Using those templates, the pipelines can be configured for different platforms, rust versions, and features quite easily from the azure-pipelines.yml file. Currently, I've added entries to the test matrix mirroring what is present in the .travis.yml file. You can see what a PR with azure pipelines would look like here: https://github.com/Perseus101/hyper/pull/2

**Comment by Perseus101** [comment]
I'm not sure if the maintainers want to wait until after 0.13 to merge this, but I think this is ready to go.

**Comment by seanmonstar** [comment]
As an update, the hyper repo just got accepted into GitHub Actions, which may make managing our CI even easier...

**Pull request closed without merging**
