### PR TITLE
[WIP] Start integration of H3 through quinn-h3

### PR DESCRIPTION
**Pull request by djc**
More as a discussion venue for now. If you agree with any prefix set of the branch let me know so that they might be merged (just cherry-pick them if you like, or we can go through a separate PR).

### CODE REVIEW

**Comment by seanmonstar** [comment]
cc #1818

**Comment by hugecheese** [comment]
How does quinn-h3 compare to Cloudflare's [quiche](https://github.com/cloudflare/quiche)?

**Comment by hugecheese** [comment]
^thoughts @seanmonstar @djc?

**Comment by djc** [comment]
I have not looked into quiche much. As far as I know, it is more focused on integrating into C environments, and less on futures-based Rust scenarios. Their H3 implementation is probably more mature than the Quinn one for now.

**Comment by djc** [comment]
I've started over on this (and the initial commit already landed separately).

**Pull request closed without merging**
