### PR TITLE
feat(header): implement ByteRangeSpec::to_satisfiable_range

### PR DESCRIPTION
**Pull request by srijs**
Implemented this for work recently, and it took us a couple of tries and careful reading of the RFC to get it right. Based on this experience, I could image it to be useful as a built-in.

Let me know what you think!

- [x] The commit messages match the guidelines in https://github.com/hyperium/hyper/blob/master/CONTRIBUTING.md#git-commit-guidelines

### CODE REVIEW

**Comment by srijs** [comment]
FYI nightly seems to fail for reasons apparently not linked to this change set

**Comment by seanmonstar** [comment]
Very cool, thanks! (Nightly failure is because nightly recently gained ASCII methods on `str`, making `AsciiExt` imports trigger a warning.)

I do admit, I had a hard-ish time understand what this problem was solving. But after looking at the tests, it seems to be "give me a range up to the Nth byte"?

**Comment by srijs** [comment]
Thanks for merging!

Yeah, so the problem it's solving is given the full length of the requested representation of a resource, just return the inclusive range that should be used to slice the data internally before returning.

So for instance, you implement an endpoint serving a file from disk, and you want to support range requests. It's a lot easier to just get a (start, end) offset that you can use to seek and read than having to deal with all the different ways a client can request a range.

Any suggestions for how to improve the docs to make this clearer?

**Comment by seanmonstar** [comment]
I see, so its trying to turn the variants into a single `a..b`, as long as `n >= b`. Maybe an example or two in the docs might help, but I'm not really sure. I've never had to use it, so my context is very shallow.

**Pull request merged**
