### PR TITLE
Update to rust-url 1.0

### PR DESCRIPTION
**Pull request by SimonSapin**
**Do not merge yet:** rust-url 1.0 is not published yet and may still get breaking changes. The goal of this PR for now is to demonstrate API usage.

Depends on:

* https://github.com/servo/rust-url/pull/176
* <s>https://github.com/alexcrichton/cookie-rs/pull/42</s>

### CODE REVIEW

**Comment by GitCop** [comment]
Thanks for contributing! Unfortunately, I'm here to tell you there were the following style issues with your Pull Request:

 * Commit: c053c9bec78ae397a3b608a055a59f244a0f3145
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/hyperium/hyper/blob/master/CONTRIBUTING.md

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
Thanks for contributing! Unfortunately, I'm here to tell you there were the following style issues with your Pull Request:

 * Commit: 9db9257bf0407edb148623feb53212f9d1a2ecea
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/hyperium/hyper/blob/master/CONTRIBUTING.md

---
This message was auto-generated by https://gitcop.com

**Comment by SimonSapin** [comment]
Still not ready to land, but what %{type} is appropriate here?

**Comment by Mr4x** [comment]
@SimonSapin use `refactor(hyper): update to rust-url 1.0`

**Comment by GitCop** [comment]
Thanks for contributing! Unfortunately, I'm here to tell you there were the following style issues with your Pull Request:

 * Commit: 353217402264578933dca89c0e7f210052c552a5
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/hyperium/hyper/blob/master/CONTRIBUTING.md

---
This message was auto-generated by https://gitcop.com

**Comment by SimonSapin** [comment]
https://crates.io/crates/url/1.0.0 is (finally!) published and this does not actually depend on https://github.com/alexcrichton/cookie-rs/pull/42 since `url` is not in `cookie`’s public API, so this is ready to land. Could you also publish it on crates.io? It’s probably a breaking change.

**Comment by seanmonstar** [comment]
Test failure:

```
src/client/request.rs:231:9: 231:55 error: this function takes 1 parameter but 2 parameters were supplied [E0061]
src/client/request.rs:231         form_urlencoded::Serializer::new(&mut body, 0).append_pair("q", "value");
                                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by SimonSapin** [comment]
Updated.

**Pull request merged**
