### PR TITLE
feat(ffi): add http1_allow_multiline_headers

### PR DESCRIPTION
**Pull request by deantvv**
Close issue #2885

### CODE REVIEW

**Review by seanmonstar — CHANGES_REQUESTED** [review]
Thanks for the PR! <3

Looks like the function names are out of sync. The `hyper_clientconn_options_http1_allow_multiline_headers` name seems preferable to me, since it is an HTTP/1 specific option. I think just running the `gen_header.sh` script should fix it up for you.

**Comment by deantvv** [comment]
> Thanks for the PR! <3
> 
> Looks like the function names are out of sync. The `hyper_clientconn_options_http1_allow_multiline_headers` name seems preferable to me, since it is an HTTP/1 specific option. I think just running the `gen_header.sh` script should fix it up for you.

Fixed in new commit.

**Review by seanmonstar — APPROVED** [review]
Thanks :D

**Comment by seanmonstar** [comment]
Would you want to add the usage in curl? If not, I can a little later, but just checking first.

**Comment by seanmonstar** [comment]
I tried to add it yesterday, and noticed that curl expects the format of multiline headers to be a little different than hyper treats them, so it'll be more work than expected. I'll need to file an issue on the curl repo.

**Pull request merged**
