### PR TITLE
fix: typo in documentation

### PR DESCRIPTION
**Pull request by afck**

### CODE REVIEW

**Comment by GitCop** [comment]
Thanks for contributing! Unfortunately, I'm here to tell you there were the following style issues with your Pull Request:

 * Commit: 00f3616a4c414cba4265d8073093d598b11185f9
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/hyperium/hyper/blob/master/CONTRIBUTING.md

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
Thanks for contributing! Unfortunately, I'm here to tell you there were the following style issues with your Pull Request:

 * Commit: 861e7b71750aa53e90e83b4a91a440498b8da374
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/hyperium/hyper/blob/master/CONTRIBUTING.md

---
This message was auto-generated by https://gitcop.com

**Comment by pyfisch** [comment]
@afck a valid commit message would be `docs(mainpage): fix typo`

**Comment by afck** [comment]
Ah, sorry! I changed it.

**Comment by seanmonstar** [comment]
Thanks!

**Pull request merged**
