### PR TITLE
Add PUT method to exported list

### PR DESCRIPTION
**Pull request by itsmontoya**

### CODE REVIEW

**Comment by itsmontoya** [comment]
I don't  understand why the commit-message-check failed, my message is less than 72 chars :/

**Comment by GuillaumeGomez** [comment]
Oh nice catch!

**Comment by seanmonstar** [comment]
The issue was that the commit message didn't match the format defined https://github.com/hyperium/hyper/blob/master/CONTRIBUTING.md#git-commit-guidelines

I modified the commit message to match, thanks!

**Comment by seanmonstar** [comment]
They are very uncommon, and you can always access them as `hyper::Method::Patch` etc.

**Pull request merged**
