### PR TITLE
feat(server): Add an ssl example

### PR DESCRIPTION
**Pull request by trezm**
Adds an example using hyper + ssl for a server.

Should resolve the closed issue #1942

### CODE REVIEW

**Comment by shirshak55** [comment]
any reason to change 100644 → 100755 ?

**Comment by trezm** [comment]
Totally, not sure why/how the permissions go changed on these files! Updated accordingly.

**Comment by Darkspirit** [comment]
https://github.com/ctz/hyper-rustls/blob/master/examples/server.rs

**Comment by trezm** [comment]
Note: I think this might currently be broken due to this change: https://github.com/hyperium/hyper/commit/71d088d3d0c062aa05459697f53bf15018cfd651, at least until tokio updates their dependencies to future 0.3.1 as well.

@Darkspirit that's awesome!! If you'd like to replace this with an example from that repo that'd be great. It just seems like for such a simple setup there should be an example to point people towards if they happen to want to have SSL on their server.

**Comment by Darkspirit** [comment]
Thank you for trying to merge a tls server example at all! :) I would be very grateful if you could update this pull request to use (the well received) rustls instead of non-rusty native-tls. Rustls and its dependencies webpki and ring are for example used by time.cloudflare.com, Google Fuchsia and Baidu. (Ring is based on Boringssl, Google's improved fork of OpenSSL, but got lots of C and C++ replaced with Rust.) It's quite sad that native-tls is spreading a bit like cancer, especially because it doesn't use Rust at places where its safety guarantees are most useful.

**Comment by trezm** [comment]
Oh totally! Wasn't even aware of the differences/benefits!! Always happier
to use the rusty alternative anyway!

**Comment by trezm** [comment]
Checking back in on this -- I have a [PR open](https://github.com/tokio-rs/tokio/pull/1873) to the tokio-tls repo to add rustls as a tls option. That being said, it looks like that might take a while to get in, which is unfortunate.

While experimenting though, I also noticed that the way the code is currently written, a long-lived http call will block request execution. Does anyone have any ideas around this? Basically because `filter_map` does not continue accepting sockets, we would need a stream op that always takes the next item and forms a new stream whose order is based on the completion time of an async closure run on each element of the original stream.

**Comment by twe4ked** [comment]
This looks awesome, it would be great to have an SSL example in the repo. I've had a search around an most of the examples I found of SSL/hyper are outdated because the async code has been moving so fast. Any updates on this?

**Comment by trezm** [comment]
I'll try to get back on this now that https://github.com/tokio-rs/tls is a
real thing!

**Comment by seanmonstar** [comment]
Thanks for the PR! I'd rather not include examples in the hyper repo selecting specific TLS libraries. I think something like this *could* be part of hyper-tls, once it gains a server API.

**Pull request closed without merging**
