### PR TITLE
perf(http) reduce memcpy

### PR DESCRIPTION
**Pull request by bfrog**
Moving Conn around caused a large number of memcpy calls to be done.
Instead use a Box and &mut self in place of moves.

Not done yet, fixing up more. Need to resolve the self.on_remove() move
issue.

This took hello.rs from ~400K req/s to close to ~500K req/s for me

### CODE REVIEW

**Comment by GitCop** [comment]
Thanks for contributing! Unfortunately, I'm here to tell you there were the following style issues with your Pull Request:

 * Commit: c88a1f01e559189e9de22a0fad6cc9eb97c4c468
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/hyperium/hyper/blob/master/CONTRIBUTING.md

---
This message was auto-generated by https://gitcop.com

**Comment by Keats** [comment]
400-500k req/s? How are you testing it?

I get ~105k req/s on a good 2 years laptop that way:
`cargo run --example hello --release`
`wrk --latency -t12 -c100 -d20s http://localhost:3000`

**Comment by bfrog** [comment]
Testing it on my core i7 desktop

```
wrk --latency -c 500 -d 30s -t 12 http://localhost:3000/                                   ✓  6952  11:14:10 
Running 30s test @ http://localhost:3000/
  12 threads and 500 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     1.30ms    1.68ms  47.35ms   88.47%
    Req/Sec    41.40k    20.85k  170.33k    69.83%
  Latency Distribution
     50%    0.88ms
     75%    1.40ms
     90%    3.20ms
     99%    6.55ms
  13930273 requests in 29.94s, 1.14GB read
Requests/sec: 465263.03
Transfer/sec:     39.05MB
```

**Comment by bluetech** [comment]
Just a data point, here's `perf record` of the above `wrk` command before this PR (only >= 2%, rust 1.9.0):

```
    17.14%  hello    libc-2.23.so        [.] __memcpy_avx_unaligned
     9.93%  hello    libc-2.23.so        [.] __memset_avx2
     5.64%  hello    hello               [.] hyper::http::h1::parse::_$LT$impl$u20$http..Http1Message$u20$for$u20$http..ServerMessage$GT$::parse::h95f4390be86b6454
     5.26%  hello    hello               [.] _$LT$hyper..http..conn..State$LT$H$C$$u20$T$GT$$GT$::update::hda2a28a5f3d7f4ac
     4.34%  hello    hello               [.] core::fmt::write::h4eb847ed3e152952
     4.00%  hello    hello               [.] _$LT$std..io..Write..write_fmt..Adaptor$LT$$u27$a$C$$u20$T$GT$$u20$as$u20$std..fmt..Write$GT$::write_str::h428ca1799ea8eabb
     3.95%  hello    hello               [.] core::fmt::Formatter::write_fmt::ha8631b2bdb82a0b7
     3.76%  hello    hello               [.] _$LT$hyper..http..conn..Conn$LT$K$C$$u20$T$C$$u20$H$GT$$GT$::on_writable::h150e5d121479d65f
     2.88%  hello    hello               [.] _$LT$mio..event_loop..EventLoop$LT$H$GT$$GT$::run_once::h42b5013245ea60d3
     2.16%  hello    hello               [.] mallocx
     2.07%  hello    hello               [.] sdallocx
     2.07%  hello    hello               [.] time::display::parse_type::h4267bac127e2a6cf
```

and after:

```
     6.57%  hello    hello               [.] _$LT$hyper..http..conn..State$LT$H$C$$u20$T$GT$$GT$::update::hda2a28a5f3d7f4ac
     6.15%  hello    hello               [.] hyper::http::h1::parse::_$LT$impl$u20$http..Http1Message$u20$for$u20$http..ServerMessage$GT$::parse::h95f4390be86b6454
     6.04%  hello    hello               [.] _$LT$mio..event_loop..EventLoop$LT$H$GT$$GT$::run_once::h42b5013245ea60d3
     5.61%  hello    hello               [.] _$LT$std..io..Write..write_fmt..Adaptor$LT$$u27$a$C$$u20$T$GT$$u20$as$u20$std..fmt..Write$GT$::write_str::h428ca1799ea8eabb
     4.92%  hello    hello               [.] core::fmt::write::h4eb847ed3e152952
     4.88%  hello    libc-2.23.so        [.] __memcpy_avx_unaligned
     4.85%  hello    hello               [.] _$LT$hyper..http..conn..Conn$LT$K$C$$u20$T$C$$u20$H$GT$$GT$::on_writable::h150e5d121479d65f
     3.28%  hello    hello               [.] rotor::handler::replacer::ha0a65d97791110f7
     3.28%  hello    hello               [.] core::fmt::Formatter::write_fmt::ha8631b2bdb82a0b7
     3.14%  hello    hello               [.] mallocx
     2.85%  hello    hello               [.] _$LT$hyper..http..conn..Conn$LT$K$C$$u20$T$C$$u20$H$GT$$GT$::ready::h4913e9752920612a
     2.76%  hello    libc-2.23.so        [.] __memset_avx2
     2.64%  hello    hello               [.] time::display::parse_type::h4267bac127e2a6cf
     2.31%  hello    hello               [.] sdallocx
```

So this PR does do what it says on the tin. I guess when the string formatter shows near the top, the situation is not bad :)

**Comment by bfrog** [comment]
This should be good now minus I guess styling/code likeability. It does what its meant to though.

Before these changes, for the hello example
``` sh
wrk --latency -c 500 -d 30s -t 12 http://localhost:3000/
Running 30s test @ http://localhost:3000/
  12 threads and 500 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     1.63ms    1.89ms  46.11ms   88.65%
    Req/Sec    38.26k    25.27k  164.33k    70.47%
  Latency Distribution
     50%  804.00us
     75%    2.93ms
     90%    3.86ms
     99%    6.60ms
  12646358 requests in 29.98s, 1.04GB read
Requests/sec: 421892.96
Transfer/sec:     35.41MB
```

After these changes for the hello example
``` sh
wrk --latency -c 500 -d 30s -t 12 http://localhost:3000/
Running 30s test @ http://localhost:3000/
  12 threads and 500 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     1.11ms    1.26ms  49.31ms   87.87%
    Req/Sec    44.22k    16.81k  153.22k    67.20%
  Latency Distribution
     50%  700.00us
     75%    1.38ms
     90%    2.69ms
     99%    5.77ms
  14946137 requests in 29.95s, 1.22GB read
Requests/sec: 499083.80
Transfer/sec:     41.88MB
```

**Comment by Ryman** [comment]
There's a lot of `self.0.foo` action, would it make sense to implement `Deref` / `DerefMut` on Conn?

**Pull request closed without merging**
