### PR TITLE
feat(server): add more request information to Handler::check_continue

### PR DESCRIPTION
**Pull request by bozaro**
I want to pull request check_continue functionality to https://github.com/iron/iron and can't get request.remote_addr in current check_continue implementation.

Unfortunately this change is incompatible with old trait :(

### CODE REVIEW

**Comment by seanmonstar** [comment]
This probably would have been the better implementation, but it's a breaking change, and I don't plan to make any more of those for the 0.9.x era... :(

**Comment by bozaro** [comment]
I think about `chunk_continue` method and came to the conclusion: this method is not good solution and I prefer to remove it.

Much better to send "100 Continue" status on first `Body::read()` call.

In this case no additional logic/callback needed for make desigion about "100 Continue":

 * If you call `Body::read()` method, then you needs to request body and hyper send to client "100 Continue";
 * If you have anought information to send final status without body, then hyper send status without "100 Continue".

I try to implement this logic on 0.9.8 branch and create a new PR.

**Comment by bozaro** [comment]
I tried to implement the logic of sending "100 Continue" status at the beginning of reading, but I could not find a way to do this without losing compatibility :(

**Comment by bozaro** [comment]
Move to issue #838

**Pull request closed without merging**
