### PR TITLE
Use tower_service::Service for hyper::service

### PR DESCRIPTION
**Pull request by LucioFranco**
cc @seanmonstar

### CODE REVIEW

**Comment by seanmonstar** [comment]
The tests need to be updated too.

**Comment by LucioFranco** [comment]
@seanmonstar done.

**Comment by LucioFranco** [comment]
I'm gonna publish tower-service as `0.3.0-alpha.1` do we want to wait for that to merge this PR?

**Comment by LucioFranco** [comment]
@seanmonstar alright this is good to go!

**Pull request merged**
