### PR TITLE
feat(server): add title case header as a server config option

### PR DESCRIPTION
**Pull request by avborhanian**
This is an attempt at a fix for #1539.

### CODE REVIEW

**Comment by seanmonstar** [comment]
Thanks for starting on this! It definitely reads clearly.

I downloaded the branch to compare benchmarks, since I've so far not implemented this because I didn't want to noticeably hurt performance. It does look like this made a couple slower, with the biggest impact being writing of `content-length: x` when not present around ~33% slower. I haven't yet built the TechEmpower server to see if turns out matter in a request life cycle (I expect it will on the pipeline benchmark).

A possibly crazy idea I thought of was to make the function actually generic over some `EncodeHeaders` trait. That'd allow inlining and branching to be pulled up to the top, and could maybe allow the the lower-case version to not need to break up names from `b": "`... 🤷‍♂️

**Comment by avborhanian** [comment]
Damn, much too slow! I'll keep benching/testing locally then. Is there a particular bench test I should look at making sure I get to a lower iter time? Or do I need to make one in this case for the content-length: 0 situation.

**Comment by seanmonstar** [comment]
The benchmarks I ran are already in the code base, you can run them yourself (compare master to your branch) via `cargo bench --features nightly --lib proto::h1::role::tests::bench_server_encode`.

And to clarify, I don't mean to say the server itself is 33% slower, just those specific benchmarks. It's possible the difference is not really noticeable in the context of a full request/response and IO cycle.

**Comment by rolftimmermans** [comment]
We are very much looking for this feature and do not mind to bear the performance costs, but I get that this might not be the same for everyone. 

Is it possible to merge this, but put the code behind a feature flag, so that it doesn't influence baseline performance in the default case?

Just wondering if there is an alternative to get this included without hurting the majority use case.

**Pull request closed without merging**
