### PR TITLE
Fix 0.9.x build with `--no-default-features --features=security-framework`

### LINKED ISSUE #819: 0.9.6 doesn't build on OS X with default-features=false, features = ["security-framework"]
I tried using hyper 0.9.6 with security-framework enabled on OS X, my Cargo.toml snippet looks like:
```toml
[dependencies.hyper]
version = "0.9.6"
default-features = false
features = ["security-framework"]
```

I get this build error:
```
   Compiling hyper v0.9.6
/Users/luser/.multirust/toolchains/stable/cargo/registry/src/github.com-88ac128001ac3a9a/hyper-0.9.6/src/client/proxy.rs:19:72: 19:86 error: type name `net::Openssl` is undefined or not in scope [E0412]
/Users/luser/.multirust/toolchains/stable/cargo/registry/src/github.com-88ac128001ac3a9a/hyper-0.9.6/src/client/proxy.rs:19 pub fn tunnel(proxy: (Cow<'static, str>, u16)) -> Proxy<HttpConnector, ::net::Openssl> {
                                                                                                                                                                                                   ^~~~~~~~~~~~~~
/Users/luser/.multirust/toolchains/stable/cargo/registry/src/github.com-88ac128001ac3a9a/hyper-0.9.6/src/client/proxy.rs:19:72: 19:86 help: run `rustc --explain E0412` to see a detailed explanation
/Users/luser/.multirust/toolchains/stable/cargo/registry/src/github.com-88ac128001ac3a9a/hyper-0.9.6/src/client/proxy.rs:19:72: 19:86 help: no candidates by the name of `Openssl` found in your project; maybe you misspelled the name or forgot to import an external crate?
error: aborting due to previous error
Could not compile `hyper`.

To learn more, run the command again with --verbose.

```

If I leave out the `features = ["security-framework"]` it builds fine. I don't have homebrew OpenSSL installed, so if I leave out the `default-features = false` it fails trying to build openssl.

### PR DESCRIPTION
**Pull request by luser**
Fixes #819

### CODE REVIEW

**Comment by GitCop** [comment]
Thanks for contributing! Unfortunately, I'm here to tell you there were the following style issues with your Pull Request:

 * Commit: c65e0c9f4bdd8bbdfc2890fc26abbd47ae68954e
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/hyperium/hyper/blob/master/CONTRIBUTING.md

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
Thanks for contributing! Unfortunately, I'm here to tell you there were the following style issues with your Pull Request:

 * Commit: 2bc5d0ff656427cbe1727456a57ba92d7918f2a2
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/hyperium/hyper/blob/master/CONTRIBUTING.md

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
Thanks for contributing! Unfortunately, I'm here to tell you there were the following style issues with your Pull Request:

 * Commit: 496db4a54081d48f1adfc8403b29a24ac64067f5
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/hyperium/hyper/blob/master/CONTRIBUTING.md

---
This message was auto-generated by https://gitcop.com

**Comment by luser** [comment]
Sorry for the zillion commits, took me a while to figure out what gitcop wanted. :)

**Comment by seanmonstar** [comment]
Woo! Thanks for the pull request!

Please excuse my tardiness. I'm traveling, very little computer time.

**Pull request merged**
