### PR TITLE
feat(server): remove addrstream struct

### PR DESCRIPTION
**Pull request by oddgrd**
Remove `AddrStream` type, it provides no benefit over `tokio::net::TcpStream`.

Closes issue #2850

This is my first contribution to this project, so I may have missed something. I am happy to take any feedback. Thanks!

### Notes
- I'm not quite sure if my changes to `AddrIncoming.poll_next_` method are correct, or if that method is actually used anywhere.
- `AddrStream` is used in documentation related to `make_service`, but as I understand it, `make_service` will be removed anyway in a different PR. Ref issue #2854

### CODE REVIEW

**Comment by seanmonstar** [comment]
Awesome, thanks for starting! I need to get the branch ready to start the new version, within the next day or two, and then I'll just start ~~blasting~~ merging :D

**Comment by oddgrd** [comment]
Cool! I'd love to work on some of the other easy issues from your stream tommorow. 

I see the CI failed because AddrStream is imported in the  `make_service` examples. I'll fix it tommorow.

**Comment by oddgrd** [comment]
I updated the `make_service` doctests to use `tokio::net::TcpStream` as well, so now the tests pass. I'll make a new PR for #2854 and delete them. 😅

**Review by seanmonstar — APPROVED** [review]
Thanks for your first contrib! :D

**Pull request merged**
