### PR TITLE
fix(rustup): rustc 1.0.0-nightly (123a754cb 2015-03-24)

### PR DESCRIPTION
**Pull request by fhartwig**
* fix `extern crate` declaration for rustc-serialize
* enable `into_cow` feature
* replace as_slice() calls by as_ref and enable `convert` feature

### CODE REVIEW

**Comment by seanmonstar** [comment]
Thanks! it looks like a fair amount of `.as_slice()` and `.to_vec()` need to be changed as well.

**Comment by fhartwig** [comment]
Sorry, I apparently forgot to run the tests. On it.

**Comment by fhartwig** [comment]
Ok, tests now build and pass on my machine. Do you want me to squash the second commit?

**Comment by seanmonstar** [comment]
Yes please.

**Comment by fhartwig** [comment]
Done.

**Comment by seanmonstar** [comment]
Excellent, thank you!

**Pull request merged**
