### PR TITLE
feat(client): add cookies support (FIXME)

### PR DESCRIPTION
**Pull request by mindcat**
#345 
Almost, but I don't know to do now.
Can you tell me where I should do?
I don't know do I can add "CookieJar" in the Client struct.
```rust
pub struct Client<C> {
    connector: C,
    cookie_jar: CookieJar,
    cookies_policy: CookiesPolicy,
    redirect_policy: RedirectPolicy,
}
```

The test
```rust
extern crate hyper;
extern crate cookie;
use hyper::Client;
use hyper::header::{
	Headers,
};
use hyper::header::Cookie as HCookie;	
use cookie::{
	Cookie,
	CookieJar
};
use hyper::client::RedirectPolicy;


fn main() {
	let c = CookieJar::new(b"f8f9eaf1ecdedff5e5b749c58115441e");
	let mut header = {
		let mut a = Headers::new();
		a.set(HCookie::from_cookie_jar(&c));
		a
	};
	c.add(Cookie::new("key".to_string(), "value".to_string()));
	c.add(Cookie::new("a2".to_string(), "3".to_string()));
	header.set(HCookie::from_cookie_jar(&c));
	let mut session = Client::new();
	session.set_redirect_policy(RedirectPolicy::FollowAll);
	// let mut cookjar = 
	let mut res = session.get("http://httpbin.org/get?a=1&f=2").headers(header.clone()).send().unwrap();
	println!("{}", res.headers);
	println!("{}", res.read_to_string().unwrap());
	let mut res = session.get("http://httpbin.org/cookies").headers(header.clone()).send().unwrap();
	println!("{}", header);
	println!("{}", res.headers);
	println!("{}", res.read_to_string().unwrap());
	let mut res = session.get("http://httpbin.org/cookies/set?k1=v1&k2=v2").headers(header.clone()).send().unwrap();
	println!("{}", header);
	println!("{}", res.headers);
	println!("{}", res.read_to_string().unwrap());
	session.set_redirect_policy(RedirectPolicy::FollowNone);
	let mut res = session.get("http://httpbin.org/cookies/set?k1=v1&k2=v2").send().unwrap();
	println!("{}", res.headers);
	println!("{}", res.read_to_string().unwrap());
}
```

### CODE REVIEW

**Comment by GitCop** [comment]
Thanks for contributing! Unfortunately, I'm here to tell you there were the following style issues with your Pull Request:

 * Commit: 08e3b8d07b8ca2ad49c634288ee8228bca8343bb
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: f48731c11ef41590cb92d05b0b28502c91df12c8
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: 5cf7e1c2c4c2eb0b7da575aa13b5655039355130
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: 321d6533e90d2dcc86f12f0f5ac19269c309501b
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/hyperium/hyper/blob/master/CONTRIBUTING.md

---
This message was auto-generated by https://gitcop.com

**Comment by mindcat** [comment]
Err... How can I combine commits that all?

**Comment by GitCop** [comment]
Thanks for contributing! Unfortunately, I'm here to tell you there were the following style issues with your Pull Request:

 * Commit: d134be98fe292fac5f78f8d5e285f50c5f19998a
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/hyperium/hyper/blob/master/CONTRIBUTING.md

---
This message was auto-generated by https://gitcop.com

**Comment by mindcat** [comment]
Ouch.

**Comment by mindcat** [comment]
Give up, I don't have any idea where can store the CookitJar now.

**Pull request closed without merging**
