### PR TITLE
feat(headers): update to unicase 2.0 and base64 0.5

### PR DESCRIPTION
**Pull request by golem131**
- [x] The commit messages match the guidelines in https://github.com/hyperium/hyper/blob/master/CONTRIBUTING.md#git-commit-guidelines

### CODE REVIEW

**Comment by GitCop** [comment]
Thanks for contributing! Unfortunately, I'm here to tell you there were the following style issues with your Pull Request:

 * Commit: fc8280e5b3fe8a964b38db8d56cfaf4bcecccf49
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/hyperium/hyper/blob/master/CONTRIBUTING.md

---
This message was auto-generated by https://gitcop.com

**Comment by seanmonstar** [comment]
Hey @golem131, thanks for this! I had done the work of upgrading to unicase 2 last night, but hadn't merged. Nonetheless, I wanted to use your work over mine, cause I get excited about contributors. However, I wanted to make use of `unicase::Ascii` and `unicase::eq_ascii` instead of `UniCase::new`, since in every situation in hyper, only ascii case is interesting. Instead of asking you to go through and change it all to match what I already had, I just merged the branch I had.

However, I'd still happily merge PR to upgrade base64!

(PS, GitCop is asking that you format the commit message a certain way, not the title of the pull request. When you already have a commit, you can alter its message via `git commit --amend`.)

**Comment by GitCop** [comment]
Thanks for contributing! Unfortunately, I'm here to tell you there were the following style issues with your Pull Request:

 * Commit: e7a598e0086fa8aafa2836747d49c1d895fcf699
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/hyperium/hyper/blob/master/CONTRIBUTING.md

---
This message was auto-generated by https://gitcop.com

**Comment by golem131** [comment]
@seanmonstar - updated

**Comment by seanmonstar** [comment]
Thanks!

**Pull request merged**
